### ISSUE TITLE
Unnecessary executable files

### ISSUE THREAD

**Issue by QuLogic** [HenrikBengtsson/R.rsp#31]
The files in `inst/rsp` appear to have the executable bit set unnecessarily. When building, this causes several warnings from R like:
```
*** WARNING: ./usr/share/R/library/R.rsp/rsp/css/rsp.css is executable but has empty or no shebang, removing executable bit
```
This is also the case for `exec/*.bat` which, since they're for Windows, might not really need that bit set either.

**Comment by HenrikBengtsson** [comment]
Thxs for reporting; coincidentally, last week I also noticed that several files across several of my packages are marked as executable.  Not sure from where and when this is originating from; many of these files were original created on Windows, hosted on SVN servers, migrated to Git, etc.  I'll put it on my to-do list to clean this up.

However, in what context you you get those warnings?  `R CMD INSTALL`, ` R CMD check`, ...?  I've never seen them.  Neither on Window nor Linux.  I'd like to be able to reproduce them so I can catch them myself if they re-occur.

**Comment by QuLogic** [comment]
Ah, my mistake, I thought those were from R, but it's actually a post-build script when producing Fedora packages.

PS, can you also change the line endings to be consistently unix ones?

**Comment by HenrikBengtsson** [comment]
Got it.

"Spurious" CRLFs fixed for next release a couple of weeks ago; https://github.com/HenrikBengtsson/R.rsp/commit/2ef90dd7e9d0d833f0fc81f9d06362a4b4e61bc1

PS. All my 30+ packages have been/are being corrected for these issues.

Note to future self:
```sh
## To list all executable files
$ find . -type f -not -path '*/\.*' -executable

## To remove the executable flag of ditto [CAREFUL]
$ find . -type f -not -path '*/\.*' -executable -exec chmod ugo-x {} \;
```
