### ISSUE TITLE
Running a rmd.rsp file through rfile begins to knit the document, as well

### ISSUE THREAD

**Issue by avalanche-cto** [HenrikBengtsson/R.rsp#33]
I'm trying to use R.rsp to populate a .rmd file that, afterwards, I knit to a pdf. However when I try to go from .rmp.rsp to .rmd, using rfile, the file appears to start knitting, and the output .rmd is not something I can further knit. Does rfile trigger knitting, somehow? Is there a way around this?

I use R.rsp extensively for .r.rsp => .r, and can also knit pdfs no problem, separately.

**Comment by HenrikBengtsson** [comment]
`rfile(..., postprocess = FALSE)` will process only the first "layer", i.e. `foo.Rmd.rsp` to `foo.Rmd`.

**Comment by avalanche-cto** [comment]
Thank you, working fine!
