### ISSUE TITLE
Vignette not showing after calling vignette()

### ISSUE THREAD

**Issue by hessakh** [HenrikBengtsson/R.rsp#38]
I followed the instructions here:
https://cran.r-project.org/web/packages/R.rsp/vignettes/R_packages-Static_PDF_and_HTML_vignettes.pdf,

but when I call `vignette(package  = "MESgenCov")` I get the message:
no vignettes found

This is the code I have in the asis file named "MESgenCov.pdf.asis":
`%\VignetteIndexEntry{R package: MESgenCov}`
`%\VignetteEngine{R.rsp::asis}`
`%\VignetteKeyword{MESP}`
`%\VignetteKeyword{covariance matrix}`
`%\VignetteKeyword{environmental monitoring}`

With the following lines in the DESCRIPTION file:

`Suggests: R.rsp`
`VignetteBuilder: R.rsp`

The pdf is also present in the `vignettes` file as instructed.

I checked for the vignette after installing the MESgenCov package from github since it's not on CRAN yet.

**Comment by HenrikBengtsson** [comment]
Start by verifying that it works with:
```sh
$ R CMD build MESgenCov
```
and then either
```sh
$ R CMD install MESgenCov_x_y.tar.gz
```
or
```r
> install.packages("MESgenCov_x_y.tar.gz", repos = NULL)
```

Only then it's worth trying to figure out why it doesn't work when installing from GitHub.  Also, you don't say how you install from GitHub, but I can imagine there are options for build vignettes or not that you need to check out.  See also if this is just your package, try for instance to install this package and see what it does.  It has static vignettes too.

**Comment by HenrikBengtsson** [comment]
OP seems to have been resolved this on their end (https://github.com/HenrikBengtsson/R.rsp/issues/43)
